const users = [
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john_doe",
        username: "john_doe",
        name: "John Doe",
        location: "San Francisco, CA",
        bio: "Software engineer passionate about clean code and open source",
        posts: 127,
        linked_by: 342,
        linked_to: 198,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane_smith",
        username: "jane_smith",
        name: "Jane Smith",
        location: "New York, NY",
        bio: "Designer | Coffee enthusiast | Creating beautiful experiences",
        posts: 89,
        linked_by: 521,
        linked_to: 287,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice_jones",
        username: "alice_jones",
        name: "Alice Jones",
        location: "Austin, TX",
        bio: "Product manager building the future of tech",
        posts: 156,
        linked_by: 289,
        linked_to: 421,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tech_mike",
        username: "tech_mike",
        name: "Mike Wilson",
        location: "Seattle, WA",
        bio: "Full-stack developer | Tech blogger | Always learning",
        posts: 234,
        linked_by: 678,
        linked_to: 445,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarahb_23",
        username: "sarahb_23",
        name: "Sarah Brown",
        location: "Boston, MA",
        bio: "Data scientist exploring the world through numbers",
        posts: 98,
        linked_by: 412,
        linked_to: 356,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=dave_codes",
        username: "dave_codes",
        name: "David Miller",
        location: "Denver, CO",
        bio: "Coding by day, gaming by night 🎮",
        posts: 176,
        linked_by: 298,
        linked_to: 512,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma_creates",
        username: "emma_creates",
        name: "Emma Davis",
        location: "Portland, OR",
        bio: "Creative director | Art lover | Storyteller",
        posts: 312,
        linked_by: 892,
        linked_to: 634,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=chris_g",
        username: "chris_g",
        name: "Chris Garcia",
        location: "Miami, FL",
        bio: "Entrepreneur | Startup enthusiast | Making ideas happen",
        posts: 145,
        linked_by: 567,
        linked_to: 389,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lisa_designs",
        username: "lisa_designs",
        name: "Lisa Martinez",
        location: "Los Angeles, CA",
        bio: "UI/UX designer crafting delightful digital experiences",
        posts: 289,
        linked_by: 743,
        linked_to: 521,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tom_dev",
        username: "tom_dev",
        name: "Tom Rodriguez",
        location: "Chicago, IL",
        bio: "Backend developer | API architect | Problem solver",
        posts: 198,
        linked_by: 456,
        linked_to: 612,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nina_art",
        username: "nina_art",
        name: "Nina Lopez",
        location: "Santa Fe, NM",
        bio: "Digital artist painting dreams into reality",
        posts: 267,
        linked_by: 834,
        linked_to: 423,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex_photos",
        username: "alex_photos",
        name: "Alex Hernandez",
        location: "San Diego, CA",
        bio: "Travel photographer capturing moments around the globe 📸",
        posts: 423,
        linked_by: 1205,
        linked_to: 789,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sophie_writes",
        username: "sophie_writes",
        name: "Sophie Gonzalez",
        location: "Nashville, TN",
        bio: "Content writer | Words are my craft",
        posts: 156,
        linked_by: 378,
        linked_to: 445,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ryan_fitness",
        username: "ryan_fitness",
        name: "Ryan Perez",
        location: "Phoenix, AZ",
        bio: "Personal trainer helping you reach your fitness goals 💪",
        posts: 312,
        linked_by: 956,
        linked_to: 567,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=olivia_music",
        username: "olivia_music",
        name: "Olivia Taylor",
        location: "Nashville, TN",
        bio: "Singer-songwriter | Music is life 🎵",
        posts: 189,
        linked_by: 623,
        linked_to: 412,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kevin_tech",
        username: "kevin_tech",
        name: "Kevin Anderson",
        location: "San Jose, CA",
        bio: "Tech reviewer | Gadget geek | Early adopter",
        posts: 245,
        linked_by: 789,
        linked_to: 534,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mia_travels",
        username: "mia_travels",
        name: "Mia Thomas",
        location: "Honolulu, HI",
        bio: "Travel blogger exploring hidden gems ✈️",
        posts: 378,
        linked_by: 1123,
        linked_to: 892,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=dan_gamer",
        username: "dan_gamer",
        name: "Daniel Jackson",
        location: "Atlanta, GA",
        bio: "Pro gamer | Streaming daily | Join the squad",
        posts: 567,
        linked_by: 2345,
        linked_to: 1234,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=amy_bakes",
        username: "amy_bakes",
        name: "Amy White",
        location: "Portland, ME",
        bio: "Baker | Pastry chef | Spreading sweetness one dessert at a time 🧁",
        posts: 289,
        linked_by: 867,
        linked_to: 445,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=brian_sports",
        username: "brian_sports",
        name: "Brian Harris",
        location: "Dallas, TX",
        bio: "Sports analyst | Fantasy football expert",
        posts: 198,
        linked_by: 534,
        linked_to: 678,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jess_fashion",
        username: "jess_fashion",
        name: "Jessica Martin",
        location: "New York, NY",
        bio: "Fashion blogger | Style is a way to say who you are 👗",
        posts: 412,
        linked_by: 1456,
        linked_to: 823,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mark_outdoors",
        username: "mark_outdoors",
        name: "Mark Thompson",
        location: "Boulder, CO",
        bio: "Outdoor enthusiast | Hiking & camping adventures 🏔️",
        posts: 345,
        linked_by: 923,
        linked_to: 712,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=laura_yoga",
        username: "laura_yoga",
        name: "Laura Lee",
        location: "San Francisco, CA",
        bio: "Yoga instructor | Mindfulness coach | Finding balance 🧘‍♀️",
        posts: 234,
        linked_by: 712,
        linked_to: 489,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=pete_runner",
        username: "pete_runner",
        name: "Peter Walker",
        location: "Boston, MA",
        bio: "Marathon runner | Running coach | One mile at a time 🏃",
        posts: 276,
        linked_by: 645,
        linked_to: 534,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rachel_chef",
        username: "rachel_chef",
        name: "Rachel Hall",
        location: "New Orleans, LA",
        bio: "Chef | Food lover | Cooking with passion 🍳",
        posts: 389,
        linked_by: 1089,
        linked_to: 756,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=steve_painter",
        username: "steve_painter",
        name: "Steven Allen",
        location: "Taos, NM",
        bio: "Abstract painter | Colors speak louder than words 🎨",
        posts: 167,
        linked_by: 489,
        linked_to: 312,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kate_blogger",
        username: "kate_blogger",
        name: "Kate Young",
        location: "Seattle, WA",
        bio: "Lifestyle blogger | Mom of two | Sharing my journey",
        posts: 423,
        linked_by: 1234,
        linked_to: 867,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jason_vlogger",
        username: "jason_vlogger",
        name: "Jason King",
        location: "Las Vegas, NV",
        bio: "Daily vlogger | Living life unfiltered 🎥",
        posts: 612,
        linked_by: 2134,
        linked_to: 1456,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maria_dancer",
        username: "maria_dancer",
        name: "Maria Wright",
        location: "Miami, FL",
        bio: "Professional dancer | Dance is my language 💃",
        posts: 298,
        linked_by: 823,
        linked_to: 612,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=paul_musician",
        username: "paul_musician",
        name: "Paul Scott",
        location: "Austin, TX",
        bio: "Guitarist | Session musician | Making music magic happen 🎸",
        posts: 245,
        linked_by: 678,
        linked_to: 534,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=hannah_reader",
        username: "hannah_reader",
        name: "Hannah Green",
        location: "Portland, OR",
        bio: "Bookworm | Literary critic | Always reading 📚",
        posts: 189,
        linked_by: 456,
        linked_to: 389,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=eric_cyclist",
        username: "eric_cyclist",
        name: "Eric Adams",
        location: "San Francisco, CA",
        bio: "Cyclist | Road racing enthusiast | Two wheels, endless roads 🚴",
        posts: 334,
        linked_by: 789,
        linked_to: 645,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=julia_artist",
        username: "julia_artist",
        name: "Julia Baker",
        location: "Brooklyn, NY",
        bio: "Contemporary artist | Gallery exhibitions | Art is freedom",
        posts: 223,
        linked_by: 612,
        linked_to: 445,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=adam_coder",
        username: "adam_coder",
        name: "Adam Nelson",
        location: "Palo Alto, CA",
        bio: "Software architect | Open source contributor | Building the future",
        posts: 367,
        linked_by: 923,
        linked_to: 712,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lily_photographer",
        username: "lily_photographer",
        name: "Lily Carter",
        location: "Charleston, SC",
        bio: "Portrait photographer | Capturing authentic moments 📷",
        posts: 278,
        linked_by: 734,
        linked_to: 523,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sam_explorer",
        username: "sam_explorer",
        name: "Sam Mitchell",
        location: "Anchorage, AK",
        bio: "Adventure seeker | Exploring the unexplored 🗺️",
        posts: 401,
        linked_by: 1045,
        linked_to: 878,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=grace_writer",
        username: "grace_writer",
        name: "Grace Roberts",
        location: "Chicago, IL",
        bio: "Fiction writer | Published author | Stories are my passion ✍️",
        posts: 312,
        linked_by: 867,
        linked_to: 612,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nick_streamer",
        username: "nick_streamer",
        name: "Nick Phillips",
        location: "Los Angeles, CA",
        bio: "Content creator | Streaming live daily | Join the community",
        posts: 534,
        linked_by: 1876,
        linked_to: 1234,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bella_stylist",
        username: "bella_stylist",
        name: "Bella Campbell",
        location: "New York, NY",
        bio: "Personal stylist | Fashion consultant | Style transformation expert",
        posts: 289,
        linked_by: 945,
        linked_to: 678,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jacob_gamer_pro",
        username: "jacob_gamer_pro",
        name: "Jacob Parker",
        location: "Seattle, WA",
        bio: "Esports player | Tournament champion | Game on! 🎮",
        posts: 678,
        linked_by: 2567,
        linked_to: 1789,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=zoe_crafts",
        username: "zoe_crafts",
        name: "Zoe Evans",
        location: "Asheville, NC",
        bio: "DIY crafter | Handmade creations | Making the world prettier ✂️",
        posts: 345,
        linked_by: 1012,
        linked_to: 756,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=luke_foodie",
        username: "luke_foodie",
        name: "Luke Turner",
        location: "San Francisco, CA",
        bio: "Food blogger | Restaurant critic | Eating my way through the city 🍕",
        posts: 456,
        linked_by: 1345,
        linked_to: 923,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=chloe_makeup",
        username: "chloe_makeup",
        name: "Chloe Collins",
        location: "Los Angeles, CA",
        bio: "Makeup artist | Beauty influencer | Enhancing natural beauty 💄",
        posts: 523,
        linked_by: 1678,
        linked_to: 1123,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=max_adventurer",
        username: "max_adventurer",
        name: "Max Stewart",
        location: "Denver, CO",
        bio: "Rock climber | Adventure photographer | Living on the edge 🧗",
        posts: 389,
        linked_by: 1089,
        linked_to: 834,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=isla_bookworm",
        username: "isla_bookworm",
        name: "Isla Morris",
        location: "Boston, MA",
        bio: "Book reviewer | Library advocate | Reading is my superpower 📖",
        posts: 267,
        linked_by: 623,
        linked_to: 489,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=owen_filmmaker",
        username: "owen_filmmaker",
        name: "Owen Rogers",
        location: "Austin, TX",
        bio: "Independent filmmaker | Telling stories through cinema 🎬",
        posts: 198,
        linked_by: 567,
        linked_to: 423,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ava_wellness",
        username: "ava_wellness",
        name: "Ava Reed",
        location: "San Diego, CA",
        bio: "Wellness coach | Holistic health advocate | Mind, body, spirit 🌿",
        posts: 312,
        linked_by: 892,
        linked_to: 645,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ethan_skater",
        username: "ethan_skater",
        name: "Ethan Cook",
        location: "Venice Beach, CA",
        bio: "Skateboarder | Street style | Shredding daily 🛹",
        posts: 423,
        linked_by: 1234,
        linked_to: 978,
        isLinked: false
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ruby_singer",
        username: "ruby_singer",
        name: "Ruby Morgan",
        location: "Nashville, TN",
        bio: "Jazz vocalist | Live performer | Music is my soul 🎤",
        posts: 234,
        linked_by: 745,
        linked_to: 534,
        isLinked: true
    },
    {
        user_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=liam_architect",
        username: "liam_architect",
        name: "Liam Bell",
        location: "Chicago, IL",
        bio: "Architect | Urban designer | Building dreams into reality 🏗️",
        posts: 189,
        linked_by: 512,
        linked_to: 378,
        isLinked: false
    }
];

export default users;