import { SpeedInsights } from "@vercel/speed-insights/next"

import { type Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"
import ThemeProviderWrapper from "@/components/ThemeProviderWrapper";
import NavbarLayoutWrapper from "@/components/NavbarLayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LinkUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        <Toaster position="top-right"/>

        <ThemeProviderWrapper>
          <NavbarLayoutWrapper>
            {children}
          </NavbarLayoutWrapper>
        </ThemeProviderWrapper>

        <SpeedInsights />
      </body>
    </html>
  );
}
